name: poke
description: Implementasi pokeapi ke flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  http:

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: '^0.9.2'
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.6
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
